In [1]:
#Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
#Credit risk database
base_credit_treat = pd.read_csv('data/base_credit_treat.csv')                           
base_credit_treat

clientid        income        age         loan  default
0            1  66155.925095  59.017015  8106.532131        0
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
4            5  66952.688845  18.584336  8770.099235        1
...        ...           ...        ...          ...      ...
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

[2000 rows x 5 columns]

In [3]:
type(base_credit_treat)

pandas.core.frame.DataFrame

In [4]:
#Division between priors and class
x_credit = base_credit_treat.iloc[:, 1:4].values

In [5]:
x_credit

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [6]:
type(x_credit)

numpy.ndarray

In [7]:
y_credit = base_credit_treat.iloc[:, 4].values

In [8]:
y_credit

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [9]:
type(y_credit)

numpy.ndarray

In [10]:
#Value scaling
x_credit[:,0].min()

20014.4894700497

In [11]:
x_credit[:,0].max()

69995.6855783239

In [12]:
x_credit[:,1].min()

18.055188510566897

In [13]:
x_credit[:,1].max()

63.971795841120205

In [14]:
x_credit[:,2].min()

1.37762959325451

In [15]:
x_credit[:,2].max()

13766.0512393337

In [16]:
x_credit[:,0].min(), x_credit[:,1].min(), x_credit[:,2].min()

(20014.4894700497, 18.055188510566897, 1.37762959325451)

In [17]:
x_credit[:,0].max(), x_credit[:,1].max(), x_credit[:,2].max()

(69995.6855783239, 63.971795841120205, 13766.0512393337)

In [19]:
#Library import for machine learning
from sklearn.preprocessing import StandardScaler

In [20]:
scale_credit = StandardScaler()

In [22]:
x_credit = scale_credit.fit_transform(x_credit)

In [23]:
x_credit[:,0].min(), x_credit[:,1].min(), x_credit[:,2].min()

(-1.7676158019964077, -1.7264145408889917, -1.4592791099462408)

In [24]:
x_credit[:,0].max(), x_credit[:,1].max(), x_credit[:,2].max()

(1.7220222385319197, 1.7393673928651967, 3.0616609141708273)

In [25]:
x_credit

array([[ 1.45393393,  1.36538093,  1.20281942],
       [-0.76217555,  0.5426602 ,  0.69642695],
       [ 0.83682073,  1.67417189,  1.17471147],
       ...,
       [-0.07122592, -0.97448519,  0.35420081],
       [-0.11000289,  1.73936739, -0.92675625],
       [ 1.682986  ,  1.14917639,  0.96381038]])